vrrp_script chk_mysql {
    script "/etc/keepalived/check_mysql.sh"
    interval 2
    timeout 2
    fall 2
    rise 1
    weight -30
}

vrrp_instance VI_SOUTH {
    state MASTER
    interface eth0
    virtual_router_id 52
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 123456
    }
    track_script {
        chk_mysql
    }
    virtual_ipaddress {
        192.168.2.100/24
    }
}
